# Generated by Django 3.2.7 on 2021-10-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20211016_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='media/userprofile/default-pro-pic.png', upload_to='userprofile'),
        ),
    ]
