# Generated by Django 3.2.7 on 2021-09-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
