# Generated by Django 3.2.7 on 2021-09-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210925_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default='', upload_to='photos/products'),
            preserve_default=False,
        ),
    ]
