# Generated by Django 3.2.7 on 2021-10-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.IntegerField(null=True),
        ),
    ]
