# Generated by Django 3.2.7 on 2021-10-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_buynowitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='coupon',
        ),
    ]
